version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: strict
    warn-unused: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/BogdanBeliy/lgtm-obs
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
